[package]
name = "black"
version = "0.0.2"
edition = "2024"
description = "A simple Black implementation in Rust"
license = "MIT"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
thiserror = "2.0.12"
