[package]
name = "black"
version = "0.0.0"
edition = "2024"
description = "A simple Black implementation in Rust"
license = "MIT"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.12"
